#cloud-config

write_files:
- path: /etc/consul.d/consul.hcl
  permissions: 0644
  owner: root
  content: |
    data_dir = "/tmp"
    datacenter = "client1"
    primary_datacenter = "monitoring"
    encrypt = "x7ohWiQjK7d/OSBvnENBXsfKxNt2GXWI7G11eejUSeI="
    advertise_addr = "172.16.3.11"
    advertise_addr_wan = "172.18.3.11"
    serf_lan = "172.16.3.11"
    serf_wan = "172.18.3.11"
    retry_join = ["172.16.3.10"]
    addresses {
        dns  = "127.0.0.1 172.17.0.1"
        http = "127.0.0.1 172.17.0.1"
        grpc = "127.0.0.1 172.17.0.1"
    }
    ports {
        grpc = 8502
    }
    node_name = "dataplane"
    ui = true
- path: /etc/nomad.d/nomad.hcl
  permissions: 0644
  owner: root
  content: |
    datacenter = "client1"
    data_dir  = "/etc/nomad.d"
    bind_addr = "172.16.3.11"
    client {
      enabled           = true
      network_interface = "eth2"
      network_speed = 1000
    }
    addresses {
      http = "127.0.0.1"
    }
    advertise {
      http = "172.16.3.11"
      rpc  = "172.16.3.11"
      serf = "172.16.3.11"
    }

runcmd:
- [ systemctl, daemon-reload ]
- [ systemctl, restart, consul ] 
- [ systemctl, restart, nomad ] 
